<?php

namespace Modules\Banpdm\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SatuanSekolahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $this->call([]);
        $now = Carbon::now();

        DB::table('tb_satuan_sekolah')->insert([
            [
                'npsn' => '10300001',
                'nama' => 'SMA Negeri 1 Padang',
                'jenjang_id' => 3,
                'status' => 'Negeri',
                'alamat' => 'Jl. Jenderal Sudirman No.1',
                'desa' => 'Belakang Tangsi',
                'kecamatan' => 'Padang Barat',
                'kode_daerah' => '1371010',
                'kode_pos' => '25118',
                'telepon' => '0751-111111',
                'email' => 'info@sman1padang.sch.id',
                'website' => 'https://sman1padang.sch.id',
                'kepala_sekolah' => 'Drs. H. Andi Saputra',
                'latitude' => -0.9470833,
                'longitude' => 100.3675000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300002',
                'nama' => 'SMP Negeri 2 Padang',
                'jenjang_id' => 2,
                'status' => 'Negeri',
                'alamat' => 'Jl. Sawahan Dalam No.10',
                'desa' => 'Sawahan',
                'kecamatan' => 'Padang Timur',
                'kode_daerah' => '1371020',
                'kode_pos' => '25123',
                'telepon' => '0751-222222',
                'email' => 'info@smpn2padang.sch.id',
                'website' => 'https://smpn2padang.sch.id',
                'kepala_sekolah' => 'Dra. Siti Rahmawati',
                'latitude' => -0.9445111,
                'longitude' => 100.3853333,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300003',
                'nama' => 'SD Negeri 05 Padang Pasir',
                'jenjang_id' => 1,
                'status' => 'Negeri',
                'alamat' => 'Jl. Veteran No.25',
                'desa' => 'Padang Pasir',
                'kecamatan' => 'Padang Barat',
                'kode_daerah' => '1371010',
                'kode_pos' => '25115',
                'telepon' => '0751-333333',
                'email' => 'info@sdn05padang.sch.id',
                'website' => null,
                'kepala_sekolah' => 'Ibu Nuraini, S.Pd',
                'latitude' => -0.9500000,
                'longitude' => 100.3611111,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300004',
                'nama' => 'SMA Islam Terpadu Al-Falah',
                'jenjang_id' => 3,
                'status' => 'Swasta',
                'alamat' => 'Jl. By Pass KM 10',
                'desa' => 'Lubuk Begalung',
                'kecamatan' => 'Lubuk Begalung',
                'kode_daerah' => '1371080',
                'kode_pos' => '25149',
                'telepon' => '0751-444444',
                'email' => 'admin@alfalahpadang.sch.id',
                'website' => 'https://alfalahpadang.sch.id',
                'kepala_sekolah' => 'Ust. Ahmad Fauzi',
                'latitude' => -0.9850000,
                'longitude' => 100.3935000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300005',
                'nama' => 'SD Muhammadiyah 1 Padang',
                'jenjang_id' => 1,
                'status' => 'Swasta',
                'alamat' => 'Jl. Thamrin No.12',
                'desa' => 'Alai Parak Kopi',
                'kecamatan' => 'Padang Utara',
                'kode_daerah' => '1371040',
                'kode_pos' => '25173',
                'telepon' => '0751-555555',
                'email' => 'sdmuh1padang@gmail.com',
                'website' => 'https://sdmuh1padang.sch.id',
                'kepala_sekolah' => 'Ahmad Riyadi, S.Pd.I',
                'latitude' => -0.9270000,
                'longitude' => 100.3620000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300006',
                'nama' => 'SMP Islam Al-Azhar Padang',
                'jenjang_id' => 2,
                'status' => 'Swasta',
                'alamat' => 'Jl. Al-Azhar No.88',
                'desa' => 'Kuranji',
                'kecamatan' => 'Kuranji',
                'kode_daerah' => '1371090',
                'kode_pos' => '25152',
                'telepon' => '0751-666666',
                'email' => 'info@alazharpadang.sch.id',
                'website' => 'https://alazharpadang.sch.id',
                'kepala_sekolah' => 'Ustadzah Lina Marlina',
                'latitude' => -0.9568000,
                'longitude' => 100.4000000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300007',
                'nama' => 'SMA Negeri 3 Padang',
                'jenjang_id' => 3,
                'status' => 'Negeri',
                'alamat' => 'Jl. Gajah Mada No.3',
                'desa' => 'Siteba',
                'kecamatan' => 'Nanggalo',
                'kode_daerah' => '1371060',
                'kode_pos' => '25144',
                'telepon' => '0751-777777',
                'email' => 'sman3@padang.sch.id',
                'website' => 'https://sman3padang.sch.id',
                'kepala_sekolah' => 'Drs. Yusri, M.Pd',
                'latitude' => -0.9325000,
                'longitude' => 100.3601000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300008',
                'nama' => 'SD Negeri 12 Pauh',
                'jenjang_id' => 1,
                'status' => 'Negeri',
                'alamat' => 'Jl. Bypass Km 12',
                'desa' => 'Pauh',
                'kecamatan' => 'Pauh',
                'kode_daerah' => '1371100',
                'kode_pos' => '25176',
                'telepon' => '0751-888888',
                'email' => 'sdn12pauh@padang.sch.id',
                'website' => null,
                'kepala_sekolah' => 'Hj. Sulastri, S.Pd',
                'latitude' => -0.9298000,
                'longitude' => 100.4755000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300009',
                'nama' => 'SMP Negeri 10 Padang',
                'jenjang_id' => 2,
                'status' => 'Negeri',
                'alamat' => 'Jl. Gunung Pangilun No.15',
                'desa' => 'Gunung Pangilun',
                'kecamatan' => 'Padang Utara',
                'kode_daerah' => '1371040',
                'kode_pos' => '25136',
                'telepon' => '0751-999999',
                'email' => 'smpn10padang@padang.sch.id',
                'website' => 'https://smpn10padang.sch.id',
                'kepala_sekolah' => 'Erna Novita, S.Pd',
                'latitude' => -0.9200000,
                'longitude' => 100.3700000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'npsn' => '10300010',
                'nama' => 'SMK Negeri 1 Padang',
                'jenjang_id' => 4, // misalnya 4 = SMK
                'status' => 'Negeri',
                'alamat' => 'Jl. Adinegoro No.3',
                'desa' => 'Lubuk Buaya',
                'kecamatan' => 'Koto Tangah',
                'kode_daerah' => '1371070',
                'kode_pos' => '25173',
                'telepon' => '0751-123123',
                'email' => 'info@smkn1padang.sch.id',
                'website' => 'https://smkn1padang.sch.id',
                'kepala_sekolah' => 'Ir. Zulkifli, M.T',
                'latitude' => -0.8880000,
                'longitude' => 100.3580000,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
